# -*- coding: utf-8 -*-
"""
AOT (compile_to_executable) coverage for cimport.

JIT execution is covered by the other cimport test files; this file proves
the same bindings work when linked into a standalone native executable.
It generates a small program that cimports one fixture library exercising
several features at once, builds it with compile_to_executable in a
subprocess, runs the produced binary, and asserts exit code and stdout.

The single fixture library covers: numeric macros, enum constants
(including a negative value), an extern global (read + write), a static
inline header function (wrapper stub), a compiled .c source function, a
struct-by-value call, and a variadic libc call (printf/snprintf).

Skipped cleanly when no C compiler/linker is available.

Note: @compile wrappers are defined at module level because pythoc requires
all @compile definitions to precede the first native call from this module.
"""
from __future__ import annotations

import os
import subprocess
import sys
import unittest


def _clang_backend_available() -> bool:
    try:
        from pythoc.cimport_clang import is_clang_backend_available
    except Exception:
        return False
    return is_clang_backend_available()


def _cc_available() -> bool:
    try:
        from pythoc.utils.cc_utils import find_available_cc
        find_available_cc()
    except RuntimeError:
        return False
    return True


_BACKEND_AVAILABLE = _clang_backend_available() and _cc_available()

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

_fixture_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'build', 'test', 'cimport_aot'))
os.makedirs(_fixture_dir, exist_ok=True)


def _write_fixture(name: str, content: str) -> str:
    path = os.path.join(_fixture_dir, name)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    return path


_HEADER = _write_fixture('aot_lib.h', '''
#define AOT_VERSION 3
#define AOT_BASE 100

enum AotCode { AOT_NEG = -5, AOT_OK = 0, AOT_MAX = 7 };

struct AotPair { int a; int b; };

extern int aot_counter;

static inline int aot_double(int x) { return 2 * x; }

int aot_bump(int delta);
struct AotPair aot_mkpair(int a, int b);
int aot_sum_pair(struct AotPair p);
''')

_SOURCE = _write_fixture('aot_lib.c', '''
#include "aot_lib.h"

int aot_counter = 1;

int aot_bump(int delta) { aot_counter += delta; return aot_counter; }
struct AotPair aot_mkpair(int a, int b) { struct AotPair p = {a, b}; return p; }
int aot_sum_pair(struct AotPair p) { return p.a + p.b; }
''')

_EXE_PATH = os.path.join(_fixture_dir, 'aot_prog_bin')

_PROGRAM = '''\
"""Generated by test_cimport_aot.py: AOT program using cimport bindings."""
import sys

from pythoc import compile, i8, i32, i64, ptr, array
from pythoc.cimport import cimport

D = {fixture_dir!r}
lib = cimport(D + '/aot_lib.h', sources=[D + '/aot_lib.c'],
              compile_sources=True, include_dirs=[D])
stdio = cimport('stdio.h', lib='c')
stdlib = cimport('stdlib.h', lib='c')

AotPair = lib.AotPair
aot_counter = lib.aot_counter


@compile
def main() -> i32:
    # static inline header function (wrapper stub)
    inline_val: i32 = lib.aot_double(6)          # 12
    # struct-by-value through the compiled C source
    p: AotPair = lib.aot_mkpair(19, 23)
    struct_val: i32 = lib.aot_sum_pair(p)        # 42
    # extern global: read + write visible to C
    base: i32 = aot_counter                      # 1
    aot_counter = 10
    bumped: i32 = lib.aot_bump(5)                # 15
    # macros and enum constants in @compile arithmetic
    macro_val: i32 = lib.AOT_BASE + lib.AOT_VERSION   # 103
    enum_val: i32 = lib.AOT_MAX + lib.AOT_NEG         # 2
    # libc calls: atoi + snprintf + printf
    parsed: i32 = stdlib.atoi("8")               # 8
    buf: array[i8, 64] = ""
    stdio.snprintf(buf, 64, "sum=%d", struct_val)
    stdio.printf("AOT inline=%d struct=%d counter=%d macro=%d enum=%d text=%s\\n",
                 inline_val, struct_val, bumped, macro_val, enum_val, buf)
    total: i32 = inline_val + struct_val + bumped + parsed + base  # 12+42+15+8+1
    return total - 36  # exit code 42


if __name__ == '__main__':
    from pythoc import compile_to_executable
    compile_to_executable(output_path={exe_path!r})
'''.format(fixture_dir=_fixture_dir, exe_path=_EXE_PATH)


@unittest.skipUnless(_BACKEND_AVAILABLE, "clang backend, cc, or linker not available")
class TestCimportAot(unittest.TestCase):
    """Build and run a native executable that uses cimport bindings."""

    @classmethod
    def setUpClass(cls):
        cls.prog_py = _write_fixture('aot_prog.py', _PROGRAM)
        env = os.environ.copy()
        env['PYTHONPATH'] = (_PROJECT_ROOT + os.pathsep
                             + env.get('PYTHONPATH', ''))
        build = subprocess.run(
            [sys.executable, cls.prog_py],
            capture_output=True, text=True, timeout=600,
            cwd=_PROJECT_ROOT, env=env, stdin=subprocess.DEVNULL,
        )
        if build.returncode != 0:
            raise RuntimeError(
                f"AOT build failed (exit {build.returncode}):\n"
                f"stdout: {build.stdout[-2000:]}\nstderr: {build.stderr[-2000:]}")
        cls.build_output = build.stdout

    def test_executable_produced(self):
        self.assertTrue(os.path.exists(_EXE_PATH))
        self.assertTrue(os.access(_EXE_PATH, os.X_OK))

    def test_executable_exit_code(self):
        result = subprocess.run(
            [_EXE_PATH], capture_output=True, text=True, timeout=60,
            stdin=subprocess.DEVNULL,
        )
        self.assertEqual(result.returncode, 42)

    def test_executable_stdout(self):
        result = subprocess.run(
            [_EXE_PATH], capture_output=True, text=True, timeout=60,
            stdin=subprocess.DEVNULL,
        )
        self.assertEqual(
            result.stdout,
            "AOT inline=12 struct=42 counter=15 macro=103 enum=2 text=sum=42\n")


if __name__ == "__main__":
    unittest.main()
